### ISSUE TITLE
好像发现一个bug

### ISSUE THREAD

**Issue by DarkmoonRabbit** [OPN48/pyGregorian2LunarCalendar#2]
> 日期    :        2020-06-12 00:00:00
> 农历数字 :       (2020, 68, 21)

我设置6月份的时候，农历数字就会变成这样~~~7月好像又正常~其他月份有没有问题就不知道了
@cuba3

**Comment by cuba3** [comment]
已修复

**Comment by cuba3** [comment]
应该是我在做二进制压缩的时候复制错行了，在闰月前后会出现日期问题

> > 日期    :        2020-06-12 00:00:00
> > 农历数字 :       (2020, 68, 21)
> 
> 我设置6月份的时候，农历数字就会变成这样~~~7月好像又正常~其他月份有没有问题就不知道了
> @cuba3

应该是我在做二进制压缩的时候复制错行了，在闰月前后会出现日期问题

**Comment by cuba3** [comment]
> > 日期    :        2020-06-12 00:00:00
> > 农历数字 :       (2020, 68, 21)
> 
> 我设置6月份的时候，农历数字就会变成这样~~~7月好像又正常~其他月份有没有问题就不知道了
> @cuba3

修复了数字问题，当时发现农历没办法完全转换成数字，存在闰月情况，所以扩了一个大于16进制的数出来，这边新增了一个是否闰月判断来耦合日期

**Comment by cuba3** [comment]
日期 	:	 2020-06-12 23:30:00
农历数字 :	 (2020, 4, 21, '闰')
农历 	:	 二零二零 庚子[鼠]年 闰四月小廿一
